name: goyasduketheft
favicon: null
layout_spectrum: 0.5748340776190162
typography_spectrum: 0.44374305638484657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8055815200787038
  lightness: 0.5944255331996828
  saturation: 0.6392277327831835
  rhythmicContrast: 0.3216187108773738
purpose: []
